### ISSUE TITLE
Research how to improve salt error  to be less generic

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#140]
## current situation:

everyone has already encountered this The problem is that this error doensn't anything useful for debugging and can be for real different reasons
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 23, in top-level template code
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'init'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 169, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 402, in render_jinja_tmpl
    buf=tmplstr)
salt.exceptions.SaltRenderError: Jinja variable 'dict object' has no attribute 'init'
[CRITICAL] Rendering SLS 'base:cluster' failed: Jinja variable 'dict object' has no attribute 'init'
local:
    Data failed to compile:
----------
    Rendering SLS 'base:cluster' failed: Jinja variable 'dict object' has no attribute 'init'
```

## expected results:

we should research and find a better error, and research if we can error-out before or in a more precise way, controlling why this happen with a more isolated small error. this will help debug and UX

**Comment by MalloZup** [comment]
closing as beeing also tracked to formula
