### ISSUE TITLE
Netweaver deployment fails

### ISSUE THREAD

**Issue by stefanotorresi** [SUSE/ha-sap-terraform-deployments#363]
A salt provisioner failure on the Netweaver nodes can be reproduced on the `master` branch

### terraform vars:

```
qemu_uri            = "qemu+ssh://<*REDACTED*>"
hana_inst_media      = "<*REDACTED*>/sap_inst_media/51053787"
base_image          = "<*REDACTED*>/SLES4SAP-15_SP0-JeOS.x86_64.qcow2"
iprange             = "192.168.124.0/24"
host_ips            = ["192.168.124.15", "192.168.124.16"]
shared_storage_type = "shared-disk"
drbd_shared_storage_type = "shared-disk"

monitoring_enabled     = true
monitoring_srv_ip      = "192.168.124.18"
ha_sap_deployment_repo = "https://download.opensuse.org/repositories/network:/ha-clustering:/Factory/SLE_15/"

reg_code  = "<*REDACTED*>"
reg_email = "<*REDACTED*>"
provisioner = "salt"

netweaver_enabled = true
netweaver_inst_media = "<*REDACTED*>/sap_inst_media"
netweaver_nfs_share    = "192.168.124.201:/HA1"
nw_ips = ["192.168.124.19", "192.168.124.20","192.168.124.21", "192.168.124.22"]

drbd_enabled = true
drbd_ips = ["192.168.124.23", "192.168.124.24"]
```

### netweaver node 1 `provisioning.log`:

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:netweaver.install_ascs' failed: Jinja error: argument of type 'StrictUndefined' is not iterable
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 10, in top-level template code
TypeError: argument of type 'StrictUndefined' is not iterable

; line 10

---
[...]

{% set instance = '{:0>2}'.format(node.instance) %}
{% set instance_name = node.sid~'_'~instance %}

{% set product_id = node.product_id|default(netweaver.product_id) %}
{% set product_id = 'NW_ABAP_ASCS:'~product_id if 'NW_ABAP_ASCS' not in product_id else product_id %}    <======================

create_ascs_inifile_{{ instance_name }}:
  file.managed:
    - source: salt://netweaver/templates/ascs.inifile.params.j2
    - name: /tmp/ascs.inifile.params
[...]
---
```

### netweaver node 2 `provisioning.log`:

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:netweaver.install_ers' failed: Jinja error: argument of type 'StrictUndefined' is not iterable
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 10, in top-level template code
TypeError: argument of type 'StrictUndefined' is not iterable

; line 10

---
[...]

{% set instance = '{:0>2}'.format(node.instance) %}
{% set instance_name = node.sid~'_'~instance %}

{% set product_id = node.product_id|default(netweaver.product_id) %}
{% set product_id = 'NW_ERS:'~product_id if 'NW_ERS' not in product_id else product_id %}    <======================

create_ers_inifile_{{ instance_name }}:
  file.managed:
    - source: salt://netweaver/templates/ers.inifile.params.j2
    - name: /tmp/ers.inifile.params
[...]
---
```

### netweaver node 3 `provisioning.log`:

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:netweaver.install_db' failed: Jinja error: argument of type 'StrictUndefined' is not iterable
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 11, in top-level template code
TypeError: argument of type 'StrictUndefined' is not iterable

; line 11

---
[...]
{% set instance = '{:0>2}'.format(node.instance) %}
{% set hana_instance = '{:0>2}'.format(netweaver.hana.instance) %}
{% set instance_name = node.sid~'_'~instance %}

{% set product_id = node.product_id|default(netweaver.product_id) %}
{% set product_id = 'NW_ABAP_DB:'~product_id if 'NW_ABAP_DB' not in product_id else product_id %}    <======================

create_db_inifile_{{ instance_name }}:
  file.managed:
    - source: salt://netweaver/templates/db.inifile.params.j2
    - name: /tmp/db.inifile.params
[...]
---
----------
    Rendering SLS 'base:netweaver.install_pas' failed: Jinja error: argument of type 'StrictUndefined' is not iterable
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 11, in top-level template code
TypeError: argument of type 'StrictUndefined' is not iterable

; line 11

---
[...]
{% set instance = '{:0>2}'.format(node.instance) %}
{% set hana_instance = '{:0>2}'.format(netweaver.hana.instance) %}
{% set instance_name = node.sid~'_'~instance %}

{% set product_id = node.product_id|default(netweaver.product_id) %}
{% set product_id = 'NW_ABAP_CI:'~product_id if 'NW_ABAP_CI' not in product_id else product_id %}    <======================

create_pas_inifile_{{ instance_name }}:
  file.managed:
    - source: salt://netweaver/templates/pas.inifile.params.j2
    - name: /tmp/pas.inifile.params
[...]
---
```

### netweaver node 4 `provisioning.log`:

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:netweaver.install_aas' failed: Jinja error: argument of type 'StrictUndefined' is not iterable
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 11, in top-level template code
TypeError: argument of type 'StrictUndefined' is not iterable

; line 11

---
[...]
{% set instance = '{:0>2}'.format(node.instance) %}
{% set hana_instance = '{:0>2}'.format(netweaver.hana.instance) %}
{% set instance_name = node.sid~'_'~instance %}

{% set product_id = node.product_id|default(netweaver.product_id) %}
{% set product_id = 'NW_DI:'~product_id if 'NW_DI' not in product_id else product_id %}    <======================

create_aas_inifile_{{ instance_name }}:
  file.managed:
    - source: salt://netweaver/templates/aas.inifile.params.j2
    - name: /tmp/aas.inifile.params
[...]
---
```

**Comment by arbulu89** [comment]
Hi @stefanotorresi,
The reason why you are having this issue is that you are using a newer version of `sapnwbootstrap-formula` with master branch. The version should be `sapnwbootstrap-formula == 0.1.8`.

For some reason, the Factory package was updated from Unstable without aligning with the Master branch. To fix this, we could cherry pick the needed commit from develop to master.

**Comment by stefanotorresi** [comment]
Thanks, Xabi! I'll try to cherrypick 2c5ca1de22c9cc8b497afd4205d5ae9bf619684d and reproduce.

**Comment by stefanotorresi** [comment]
@arbulu89 I have ported that cherry-pick in master, and now I have a different failure, only in nodes 3 and 4:

```
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [INFO    ] ERROR      2020-02-24 12:36:44.190 (root/sapinst) (startInstallation) [CSiStepExecute.cpp:1055] id=controller.stepExecuted errno=FCO-00011 CSiStepExecute::execute()
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [INFO    ] The step checkABAP with step key |NW_DI|ind|ind|ind|ind|0|0|NW_GetSidFromProfiles|ind|ind|ind|ind|getSid|0|NW_readProfileDir|ind|ind|ind|ind|readProfile|0|NW_checkModel|ind|ind|ind|ind|check|0|NW_checkModel_systemCompleteness|ind|ind|ind|ind|complete|0|checkABAP was executed with status ERROR. Reason: The step has requested the termination of the service execution.
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [INFO    ]
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [INFO    ] INFO       2020-02-24 12:36:44.203 (root/sapinst) (startInstallation) [syuxcdir.cpp:147] id=syslib.filesystem.removedDirectory CSyDirectoryImpl::sap_remove(ISyFSErrorHandler * pErrorHandler)
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [INFO    ] Removed directory /root/.sapinst/netweaver04/25726.
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [INFO    ]
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [ERROR   ] =>sapparam(1c): No Profile used.
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [ERROR   ] =>sapparam: SAPSYSTEMNAME neither in Profile nor in Commandline
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [ERROR   ] ################################################
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [ERROR   ] Abort execution because service selection
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [ERROR   ]       is not possible without GUI.
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [ERROR   ] ################################################
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [ERROR   ]
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [ERROR   ] SAP Netweaver installation failed
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [INFO    ] Completed state [ha1] at time 12:36:44.316595 (duration_in_ms=45340.025)
module.netweaver_node.null_resource.netweaver_node_provisioner[3] (remote-exec): [INFO    ] State result does not match retry until value, state will be re-run in 600 seconds
```

this basically will repeat on and on until terraform times out.

**Comment by arbulu89** [comment]
Hi @stefanotorresi , after setting the `nw_virtual_ips` variable properly, it looks like you have fixed the issue, right?
In that case, can we close the issue? Or do you want to create some PR improving the documentation to avoid this error in the future?

**Comment by stefanotorresi** [comment]
Yeah, as soon as I can get `ḍevelop` to deploy I will close this. :wink:

**Comment by stefanotorresi** [comment]
I've got the following salt provisioner failure on node 1, so I guess all the following nodes fail consequently:
```
----------
          ID: wait_until_systems_installed
    Function: netweaver.check_instance_present
        Name: ENQREP
      Result: False
     Comment: Attempt 1: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 2: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 3: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 4: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 5: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 6: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 7: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 8: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 9: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 10: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 11: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 12: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 13: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 14: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 15: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 16: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 17: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 18: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Attempt 19: Returned a result of "False", with the following comment: "Netweaver instance ENQREP is not present"
              Netweaver instance ENQREP is not present
     Started: 12:27:20.865558
    Duration: 573732.513 ms
     Changes:   
----------
          ID: update_sapservices_HA1_00
    Function: netweaver.sapservices_updated
        Name: ascs
      Result: False
     Comment: the required sap instances to make these changes are not installed or running
     Started: 12:36:55.135857
    Duration: 236.145 ms
     Changes:   
```

**Comment by Simranpal** [comment]
Hi @stefanotorresi is the issue resolved? Could you share the salt logs, sap installer logs `/tmp/swpm_unnattended/sapinst.log`
