### ISSUE TITLE
Idempotency of project

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#364]
This issue will track some issue we have when re-running 2/more times the states or terraform apply.

it will serve as log/issue tracker of problems

# Issues fixed:

- 01 (status: not fixed) : running deployment.sh script twice fail

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 24, in top-level template code
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'init'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 169, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 402, in render_jinja_tmpl
    buf=tmplstr)
salt.exceptions.SaltRenderError: Jinja variable 'dict object' has no attribute 'init'
[CRITICAL] Rendering SLS 'base:cluster' failed: Jinja variable 'dict object' has no attribute 'init'
local:
    Data failed to compile:
----------
    Rendering SLS 'base:cluster' failed: Jinja variable 'dict object' has no attribute 'init'
```

**Comment by MalloZup** [comment]
- [ ] to test: . Test with iscsi too

**Comment by MalloZup** [comment]
when running the deployment.sh script 2 times this state fails:

- [ ] 

```         ID: hana_inst_directory
    Function: file.directory
        Name: /root/hana_inst_media
      Result: False
     Comment: Failed to change user to root
     Started: 17:16:35.400492
    Duration: 3.586 ms
     Changes:   
```

**Comment by MalloZup** [comment]
closing for moment since it is a never-ending task,
