### ISSUE TITLE
hanadb_exporter not finding SAP python dependencies in SLE12SP5

### ISSUE THREAD

**Issue by stefanotorresi** [SUSE/ha-sap-terraform-deployments#492]
While testing in SLE12SP5 i've found that `hanadb_exporters` fails to start with the following log:

```
Jun 04 12:19:41 hana01 systemd[1]: Started Cluster Controlled prometheus-hanadb_exporter@PRD_HDB00.
Jun 04 12:19:41 hana01 hanadb_exporter[21772]: 2020-06-04 12:19:41,697 ERROR hanadb_exporter Traceback (most recent call last):
                                                 File "/usr/bin/hanadb_exporter", line 9, in <module>
                                                   main.run()
                                                 File "/usr/lib/python3.4/site-packages/hanadb_exporter/main.py", line 118, in run
                                                   dbs = db_manager.DatabaseManager()
                                                 File "/usr/lib/python3.4/site-packages/hanadb_exporter/db_manager.py", line 37, in __init__
                                                   self._system_db_connector = hdb_connector.HdbConnector()
                                                 File "/usr/lib/python3.4/site-packages/shaptools/hdb_connector/__init__.py", line 34, in __new__
                                                   raise base_connector.DriverNotAvailableError('dbapi nor pyhdb are installed')
                                               shaptools.hdb_connector.connectors.base_connector.DriverNotAvailableError: dbapi nor pyhdb are installed
Jun 04 12:19:41 hana01 hanadb_exporter[21772]: 2020-06-04 12:19:41,697 ERROR hanadb_exporter Traceback (most recent call last):
Jun 04 12:19:41 hana01 hanadb_exporter[21772]:   File "/usr/bin/hanadb_exporter", line 9, in <module>
Jun 04 12:19:41 hana01 hanadb_exporter[21772]:     main.run()
Jun 04 12:19:41 hana01 hanadb_exporter[21772]:   File "/usr/lib/python3.4/site-packages/hanadb_exporter/main.py", line 118, in run
Jun 04 12:19:41 hana01 hanadb_exporter[21772]:     dbs = db_manager.DatabaseManager()
Jun 04 12:19:41 hana01 hanadb_exporter[21772]:   File "/usr/lib/python3.4/site-packages/hanadb_exporter/db_manager.py", line 37, in __init__
Jun 04 12:19:41 hana01 hanadb_exporter[21772]:     self._system_db_connector = hdb_connector.HdbConnector()
Jun 04 12:19:41 hana01 hanadb_exporter[21772]:   File "/usr/lib/python3.4/site-packages/shaptools/hdb_connector/__init__.py", line 34, in __new__
Jun 04 12:19:41 hana01 hanadb_exporter[21772]:     raise base_connector.DriverNotAvailableError('dbapi nor pyhdb are installed')
Jun 04 12:19:41 hana01 hanadb_exporter[21772]: shaptools.hdb_connector.connectors.base_connector.DriverNotAvailableError: dbapi nor pyhdb are installed
Jun 04 12:19:41 hana01 systemd[1]: prometheus-hanadb_exporter@PRD_HDB00.service: Main process exited, code=exited, status=1/FAILURE
Jun 04 12:19:41 hana01 systemd[1]: prometheus-hanadb_exporter@PRD_HDB00.service: Unit entered failed state.
Jun 04 12:19:41 hana01 systemd[1]: prometheus-hanadb_exporter@PRD_HDB00.service: Failed with result 'exit-code'.
Jun 04 12:19:47 hana01 systemd[1]: Stopped SAP HANA database metrics exporter.
```

The related salt state appears to be executed successfully though:

```
----------
ID: install_pydbapi_client
    Function: cmd.run
        Name: /usr/bin/python -m pip install /tmp/pydbapi/hdbcli-*.tar.gz
      Result: True
     Comment: Command "/usr/bin/python -m pip install /tmp/pydbapi/hdbcli-*.tar.gz" run
     Started: 12:17:32.105523
    Duration: 15332.959 ms
     Changes:   
              ----------
              pid:
                  8549
              retcode:
                  0
              stderr:
                  tornado 4.2.1 requires backports.ssl_match_hostname, which is not installed.
                  You are using pip version 10.0.1, however version 20.2b1 is available.
                  You should consider upgrading via the 'pip install --upgrade pip' command.
              stdout:
                  Processing /tmp/pydbapi/hdbcli-2.4.126.tar.gz
                  Installing collected packages: hdbcli
                    Running setup.py install for hdbcli: started
                      Running setup.py install for hdbcli: finished with status 'done'
                  Successfully installed hdbcli
----------
```

You can reproduce this by trying to deploy HANA with the `SLES4SAP-12SP5-JeOS.x86_64` source image.

**Comment by arbulu89** [comment]
I know what's going on. The stupid of me added a condition to install the packages in py2 or py3. This doesn't make sense, as hanadb_exporter runs always python3. Here the issue: https://github.com/SUSE/saphanabootstrap-formula/blob/master/hana/monitoring.sls#L23
We would need to remove this conditions, and always install in py3.
Hopefully, pyhon3-pip is available for SLE12, otherwise we have to do something else...

**Comment by stefanotorresi** [comment]
ahh yes, `python3-pip` will be available in SLE12 as long as the Public Cloud Module is registered.

**Comment by arbulu89** [comment]
@stefanotorresi I tried in the past to install the python `tar.gz` without `pip` (running `python setup.py install` and things like that). Maybe we could give a try to this...
Otherwise, we will need add the cloud module in libvirt too using tfvars. This is done for the cloud providers always. It's something that we need to consider

**Comment by diegoakechi** [comment]
@stefanotorresi @arbulu89 Even that I would love to ignore on extra dependency, I think we should stick to the SAP documentation on how to install it... :disappointed_relieved:

**Comment by stefanotorresi** [comment]
I don't think this is going to be a big problem; we can stick with `pip`, as long as we properly document the need of the SLE module in SLE12.
