### ISSUE TITLE
Error Deploing Monitoring Instance - error in pre-deployment phase

### ISSUE THREAD

**Issue by picoroma** [SUSE/ha-sap-terraform-deployments#603]
Enable the Monitoring Instance with :
monitoring_enabled = true
monitoring_srv_ip = "10.0.0.253"

Give me an error durint the "pre-deployment" step of the procedure.

There are a lot of error into the pre-deployment.lof file (see attach). All are related to
# Error loading module.boto3_xxxxxx

[salt-predeployment.log](https://github.com/SUSE/ha-sap-terraform-deployments/files/5578149/salt-predeployment.log)

As a result Grafana seems to be NOT installed at all. Even if Prometheus and Loki is istalled.

**Comment by arbulu89** [comment]
@stefanotorresi @MalloZup Could you have a look on this?
I can identify the next error (part of the log file) as the root cause:

```
2020-11-21 18:08:27,484 [salt.utils.lazy  :105 ][DEBUG   ][1336] LazyLoaded file.blockreplace
2020-11-21 18:08:27,484 [salt.state       :1869][INFO    ][1336] Running state [/etc/grafana/grafana.ini] at time 18:08:27.484661
2020-11-21 18:08:27,484 [salt.state       :1902][INFO    ][1336] Executing state file.blockreplace for [/etc/grafana/grafana.ini]
2020-11-21 18:08:27,487 [salt.utils.lazy  :105 ][DEBUG   ][1336] LazyLoaded file.blockreplace
2020-11-21 18:08:27,488 [salt.utils.lazy  :105 ][DEBUG   ][1336] LazyLoaded files.get_encoding
2020-11-21 18:08:27,489 [salt.loaded.int.states.file:5118][ERROR   ][1336] Encountered error managing block
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/states/file.py", line 5116, in blockreplace
    append_newline=append_newline)
  File "/usr/lib/python3.6/site-packages/salt/modules/file.py", line 2722, in blockreplace
    'Unterminated marked block. End of file reached before marker_end.'
salt.exceptions.CommandExecutionError: Unterminated marked block. End of file reached before marker_end.
2020-11-21 18:08:27,497 [salt.state       :323 ][ERROR   ][1336] Encountered error managing block: Unterminated marked block. End of file reached before marker_end.. See the log for details.
2020-11-21 18:08:27,497 [salt.state       :2051][INFO    ][1336] Completed state [/etc/grafana/grafana.ini] at time 18:08:27.497670 (duration_in_ms=13.009)
```

**Comment by stefanotorresi** [comment]
this is fixed already by #595, do you want me to backport that to master?

**Comment by arbulu89** [comment]
@stefanotorresi You are right, I looked the wrong branch...
@picoroma So this issue should be solved in `devel` branch

**Comment by picoroma** [comment]
Tested with DEVEL Branch. It works fine.
Can I use also the main branch?
P.

**Comment by arbulu89** [comment]
> Tested with DEVEL Branch. It works fine.
> Can I use also the main branch?
> P.

Not yet. The fix has not reached `master` branch yet.
We still have not scheduled a new version that will bring this fix to a stable version
