### ISSUE TITLE
`modules/cluster_node` does not install `promtail`

### ISSUE THREAD

**Issue by yeoldegrove** [SUSE/ha-sap-terraform-deployments#707]
**Used cloud platform**
all

**Used SLES4SAP version**
SLES15SP2

**Used client machine OS**
Linux

**Expected behaviour vs observed behaviour**
`modules/cluster_node` should install installs `loki` and `promtail` and start the `promtail` service if monitoring is enabled.
`promtail` however is not installed and the salt run fails.

**Possible Reason**
https://github.com/SUSE/ha-sap-terraform-deployments/blob/14b543b6e55bc69e5a012fdad7c3a8bf4675f84c/salt/cluster_node/monitoring.sls#L50
The `loki` pkg is installed here as a requirement for `promtail`. However `promtail` is a subpackage which is not explicitly installed if you install `loki`:
https://build.opensuse.org/package/view_file/network:ha-clustering:sap-deployments:devel/loki/loki.spec?expand=1

**How to reproduce**
Run salt code of `modules/cluster_node`.

**Used terraform.tfvars**
Paste here the used `terraform.tfvars` file content. If the file has any secret, change them by dummy information.
```
ha_sap_deployment_repo = "https://download.opensuse.org/repositories/network:/ha-clustering:/sap-deployments:/devel/SLE_15_SP2/"
```

**Logs**
```
2021-06-11 08:41:16,563 [salt.state       :1881][INFO    ][1720] Running state [/etc/loki/promtail.yaml] at time 08:41:16.563499
2021-06-11 08:41:16,563 [salt.state       :1914][INFO    ][1720] Executing state file.managed for [/etc/loki/promtail.yaml]
2021-06-11 08:41:16,566 [salt.utils.lazy  :105 ][DEBUG   ][1720] LazyLoaded file.source_list
2021-06-11 08:41:16,567 [salt.utils.lazy  :105 ][DEBUG   ][1720] LazyLoaded cp.hash_file
2021-06-11 08:41:16,569 [salt.fileclient  :1101][DEBUG   ][1720] In saltenv 'predeployment', looking at rel_path 'cluster_node/templates/promtail.yaml.j2' to resolve 'salt://cluster_node/templates/promtail.yaml.j2'
2021-06-11 08:41:16,569 [salt.fileclient  :1109][DEBUG   ][1720] In saltenv 'predeployment', ** considering ** path '/var/cache/salt/minion/files/predeployment/cluster_node/templates/promtail.yaml.j2' to resolve 'salt://cluster_node/templates/promtail.yaml.j2'
2021-06-11 08:41:16,569 [salt.fileclient  :1129][DEBUG   ][1720] Fetching file from saltenv 'predeployment', ** attempting ** 'salt://cluster_node/templates/promtail.yaml.j2'
2021-06-11 08:41:16,569 [salt.fileclient  :1157][DEBUG   ][1720] No dest file found
2021-06-11 08:41:16,570 [salt.fileclient  :1238][INFO    ][1720] Fetching file from saltenv 'predeployment', ** done ** 'cluster_node/templates/promtail.yaml.j2'
2021-06-11 08:41:16,570 [salt.utils.jinja :91  ][DEBUG   ][1720] Jinja search path: ['/var/cache/salt/minion/files/predeployment']
2021-06-11 08:41:16,573 [salt.state       :321 ][INFO    ][1720] File changed:
New file
2021-06-11 08:41:16,573 [salt.state       :2063][INFO    ][1720] Completed state [/etc/loki/promtail.yaml] at time 08:41:16.573880 (duration_in_ms=10.382)
2021-06-11 08:41:16,574 [salt.utils.lazy  :105 ][DEBUG   ][1720] LazyLoaded group.present
2021-06-11 08:41:16,575 [salt.state       :1881][INFO    ][1720] Running state [systemd-journal] at time 08:41:16.575412
2021-06-11 08:41:16,575 [salt.state       :1914][INFO    ][1720] Executing state group.present for [systemd-journal]
2021-06-11 08:41:16,580 [salt.utils.lazy  :105 ][DEBUG   ][1720] LazyLoaded group.info
2021-06-11 08:41:16,582 [salt.utils.lazy  :105 ][DEBUG   ][1720] LazyLoaded cmd.retcode
2021-06-11 08:41:16,582 [salt.loaded.int.module.cmdmod:395 ][INFO    ][1720] Executing command gpasswd in directory '/root'
2021-06-11 08:41:16,609 [salt.loaded.int.module.cmdmod:838 ][DEBUG   ][1720] stdout: Adding user loki to group systemd-journal
2021-06-11 08:41:16,675 [salt.utils.lazy  :105 ][DEBUG   ][1720] LazyLoaded test.ping
2021-06-11 08:41:16,676 [salt.state       :321 ][INFO    ][1720] {'Final': 'All changes applied successfully'}
2021-06-11 08:41:16,676 [salt.state       :2063][INFO    ][1720] Completed state [systemd-journal] at time 08:41:16.676336 (duration_in_ms=100.923)
2021-06-11 08:41:17,698 [salt.config      :2116][DEBUG   ][1720] Reading configuration from /etc/salt/minion
2021-06-11 08:41:17,699 [salt.config      :3619][DEBUG   ][1720] Using cached minion ID from /etc/salt/minion_id: vmdrbd01.internal.cloudapp.net
2021-06-11 08:41:17,914 [salt.utils.lazy  :109 ][DEBUG   ][1720] Could not LazyLoad boto3.assign_funcs: 'boto3.assign_funcs' is not available.
2021-06-11 08:41:17,914 [salt.loader      :1728][DEBUG   ][1720] Error loading module.boto3_elasticsearch: __init__ failed
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1721, in _load_module
    module_init(self.opts)
  File "/usr/lib/python3.6/site-packages/salt/modules/boto3_elasticsearch.py", line 92, in __init__
    __utils__['boto3.assign_funcs'](__name__, 'es')
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1269, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python3.6/site-packages/salt/utils/lazy.py", line 111, in __getitem__
    raise KeyError(key)
KeyError: 'boto3.assign_funcs'
2021-06-11 08:41:18,249 [salt.loaded.int.module.config:483 ][DEBUG   ][1720] key: ifttt.secret_key, ret: _|-
2021-06-11 08:41:18,249 [salt.loaded.int.module.config:483 ][DEBUG   ][1720] key: ifttt:secret_key, ret: _|-
2021-06-11 08:41:18,865 [salt.loaded.int.module.config:483 ][DEBUG   ][1720] key: pushbullet.api_key, ret: _|-
2021-06-11 08:41:18,865 [salt.loaded.int.module.config:483 ][DEBUG   ][1720] key: pushbullet:api_key, ret: _|-
2021-06-11 08:41:19,280 [salt.loaded.int.module.config:483 ][DEBUG   ][1720] key: victorops.api_key, ret: _|-
2021-06-11 08:41:19,280 [salt.loaded.int.module.config:483 ][DEBUG   ][1720] key: victorops:api_key, ret: _|-
2021-06-11 08:41:24,745 [salt.loaded.int.module.win_dsc:43  ][DEBUG   ][1720] DSC: Only available on Windows systems
2021-06-11 08:41:24,758 [salt.loaded.int.module.win_psget:35  ][DEBUG   ][1720] Module PSGet: Only available on Windows systems
2021-06-11 08:41:24,790 [salt.utils.lazy  :105 ][DEBUG   ][1720] LazyLoaded service.running
2021-06-11 08:41:24,791 [salt.state       :1881][INFO    ][1720] Running state [promtail] at time 08:41:24.791750
2021-06-11 08:41:24,792 [salt.state       :1914][INFO    ][1720] Executing state service.running for [promtail]
2021-06-11 08:41:24,792 [salt.loaded.int.module.cmdmod:395 ][INFO    ][1720] Executing command systemctl in directory '/root'
2021-06-11 08:41:24,802 [salt.loaded.int.module.cmdmod:838 ][DEBUG   ][1720] stdout: Unit promtail.service could not be found.
2021-06-11 08:41:24,802 [salt.loaded.int.module.cmdmod:842 ][DEBUG   ][1720] retcode: 4
```

**Comment by yeoldegrove** [comment]
This is already fixed in https://github.com/SUSE/ha-sap-terraform-deployments/pull/705
